# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTlEWVDEH-H49fOhXLrMDc7EG8CE-EuZ
"""

import os
print(os.listdir())

import pandas as pd

df = pd.read_csv("PhiUSIIL_Phishing_URL_Dataset.csv")

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print(df["label"].value_counts())

from feature_extraction import extract_url_features

print("feature_extraction.py loaded successfully.")

test_url = "https://www.southbankmosaics.com"

features = extract_url_features(test_url)

print("Extracted features:")

for name, value in features.items():
    print(name, "=", value)

url_feature_rows = []

for url in df["URL"]:
    features = extract_url_features(url)
    url_feature_rows.append(features)

X = pd.DataFrame(url_feature_rows)

y = df["label"].copy()

print("Feature extraction completed.")
print("X shape:", X.shape)
print("y shape:", y.shape)

print(X.head())

print("\nMissing values:")
print(X.isnull().sum())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Model training completed.")

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    average="weighted"
)

recall = recall_score(
    y_test,
    y_pred,
    average="weighted"
)

f1 = f1_score(
    y_test,
    y_pred,
    average="weighted"
)

print("\nEvaluation Results")
print("------------------")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-score :", f1)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

import joblib

joblib.dump(
    model,
    "url_phishing_model.pkl"
)

joblib.dump(
    list(X.columns),
    "url_model_features.pkl"
)

print("\nFiles saved successfully:")
print("url_phishing_model.pkl")
print("url_model_features.pkl")

def predict_url(url):

    features = extract_url_features(url)

    input_data = pd.DataFrame([features])

    input_data = input_data[X.columns]

    prediction = model.predict(input_data)[0]

    probabilities = model.predict_proba(input_data)[0]

    confidence = max(probabilities)

    if prediction == 1:
        result = "Legitimate"
    else:
        result = "Phishing"

    return {
        "prediction": int(prediction),
        "result": result,
        "confidence": round(float(confidence), 3)
    }


test_url = "https://www.southbankmosaics.com"

result = predict_url(test_url)

print("URL:", test_url)
print("Prediction:", result["prediction"])
print("Result:", result["result"])
print("Confidence:", result["confidence"])

test_url = "http://www.teramill.com"

result = predict_url(test_url)

print("URL:", test_url)
print("Prediction:", result["prediction"])
print("Result:", result["result"])
print("Confidence:", result["confidence"])

